### ISSUE TITLE
Couldn't install

### ISSUE THREAD

**Issue by rickyalfaray** [danillo-alvarenga/tncomp_finder#1]
Dear danillo-alvarenga,
Hi, thank you for providing this program.

I would like to try this program, but I couldn't succeed to install it.
I still a beginner in programming, could you please help me with a clear step-by-step?
Currently, I'm using Linux-based.
I already installed blast (conda install blast), prodigal (conda install prodigal) and Python-3.7.0 (by following: wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz --> tar -xzf Python-3.7.0.tgz --> cd Python-3.7.0/ --> ./configure --> make)
I already downloaded and unzipped the program in the directory that I want.
I created a new environment. 
Here is the directory that I want and the files: 
>cd /data/Ricky/Software/transposone/tncomp_finder-1.0.0
>ls
db  LICENSE  README.md  TnComp_finder.py

but when I do 
> echo 'export PATH=$PATH'$(pwd) >> /data/Ricky/Software/transposone/tncomp_finder-1.0.0/TnComp_finder.py
> source /data/Ricky/Software/transposone/tncomp_finder-1.0.0/TnComp_finder.py

it becomes an error and this appeared:

import: unable to open X server `' @ error/import.c/ImportImageCommand/344.
import: unable to open X server `' @ error/import.c/ImportImageCommand/344.
import: unable to open X server `' @ error/import.c/ImportImageCommand/344.
import: unable to open X server `' @ error/import.c/ImportImageCommand/344.
bash: from: command not found...
bash: from: command not found...
bash: from: command not found...
bash: from: command not found...
bash: from: command not found...
bash: from: command not found...
bash: from: command not found...
bash: from: command not found...
-bash: /data/Ricky/Software/transposone/tncomp_finder-1.0.0/TnComp_finder.py: line 37: syntax error near unexpected token `('
-bash: /data/Ricky/Software/transposone/tncomp_finder-1.0.0/TnComp_finder.py: line 37: `parser = argparse.ArgumentParser(description="composite transposon finder",'

My questions are:
1. Is the installment of the blast, prodigal, and Python-3.7.0 correct?
2. Is there something wrong with my installation step?

Thank you

Kind regards,
Ricky

**Comment by danillo-alvarenga** [comment]
Dear Ricky,

I recommend using the package manager of your distro instead of conda for installing the dependencies. So if you are using a Debian-based distro, please install them with apt using these commands:
`sudo apt install ncbi-blast+`
`sudo apt install prodigal`
`sudo apt install python3-biopython`

Then you can get into the directory where you downloaded the files and export that directory to your `.bashrc` file so you can call the script in any directory without having to type the full path:
`cd /data/Ricky/Software/transposone/tncomp_finder-1.0.0`
`echo 'export PATH=$PATH:'$(pwd) >> ~/.bashrc;  source ~/.bashrc`

Don't edit these commands, just copy and paste them exactly as they are.

Best wishes,
Danillo

**Comment by danillo-alvarenga** [comment]
Closing issue as solved following two weeks of inactivity after a solution was provided.
